services:
  installer:
    container_name: azuracast_installer
    image: 'ghcr.io/talex0909/azuracast:latest'
    volumes:
      - './:/installer'
    restart: 'no'
    entrypoint: docker_installer
    command: install
    privileged: true
